# Generated by Django 4.1.7 on 2023-04-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtecContreLesMenacesLv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('enonce', models.CharField(max_length=255)),
                ('reponse1', models.CharField(max_length=255)),
                ('reponse2', models.CharField(max_length=255)),
                ('reponse3', models.CharField(max_length=255)),
                ('reponce4', models.CharField(max_length=255)),
                ('reponseVrai', models.CharField(max_length=255)),
                ('reponse', models.CharField(max_length=255)),
                ('explication', models.CharField(default='', max_length=1000)),
                ('qcm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProtecContreLesMenacesLv3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('enonce', models.CharField(max_length=255)),
                ('reponse1', models.CharField(max_length=255)),
                ('reponse2', models.CharField(max_length=255)),
                ('reponse3', models.CharField(max_length=255)),
                ('reponce4', models.CharField(max_length=255)),
                ('reponseVrai', models.CharField(max_length=255)),
                ('reponse', models.CharField(max_length=255)),
                ('explication', models.CharField(default='', max_length=1000)),
                ('qcm', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmpcm1pourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmpcm2pourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmpcm3pourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmpcmTpourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validepcm1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validepcm2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validepcm3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validepcmT',
            field=models.BooleanField(default=False),
        ),
    ]
