# Generated by Django 4.1.7 on 2023-04-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_proteccontrelesmenaceslv1_proteccontrelesmenaceslv3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HygienenumeriqueLV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('enonce', models.CharField(max_length=255)),
                ('reponse1', models.CharField(max_length=255)),
                ('reponse2', models.CharField(max_length=255)),
                ('reponse3', models.CharField(max_length=255)),
                ('reponce4', models.CharField(max_length=255)),
                ('reponseVrai', models.CharField(max_length=255)),
                ('reponse', models.CharField(max_length=255)),
                ('explication', models.CharField(default='', max_length=1000)),
                ('qcm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HygienenumeriqueLV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('enonce', models.CharField(max_length=255)),
                ('reponse1', models.CharField(max_length=255)),
                ('reponse2', models.CharField(max_length=255)),
                ('reponse3', models.CharField(max_length=255)),
                ('reponce4', models.CharField(max_length=255)),
                ('reponseVrai', models.CharField(max_length=255)),
                ('reponse', models.CharField(max_length=255)),
                ('explication', models.CharField(default='', max_length=1000)),
                ('qcm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HygienenumeriqueLV3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('enonce', models.CharField(max_length=255)),
                ('reponse1', models.CharField(max_length=255)),
                ('reponse2', models.CharField(max_length=255)),
                ('reponse3', models.CharField(max_length=255)),
                ('reponce4', models.CharField(max_length=255)),
                ('reponseVrai', models.CharField(max_length=255)),
                ('reponse', models.CharField(max_length=255)),
                ('explication', models.CharField(default='', max_length=1000)),
                ('qcm', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmhn1pourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmhn2pourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmhn3pourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmhnTpourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validehn1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validehn2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validehn3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validehnT',
            field=models.BooleanField(default=False),
        ),
    ]
