# Generated by Django 4.1.7 on 2023-04-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_hygienenumeriquelv1_hygienenumeriquelv2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdpEtAuthLv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('enonce', models.CharField(max_length=255)),
                ('reponse1', models.CharField(max_length=255)),
                ('reponse2', models.CharField(max_length=255)),
                ('reponse3', models.CharField(max_length=255)),
                ('reponce4', models.CharField(max_length=255)),
                ('reponseVrai', models.CharField(max_length=255)),
                ('reponse', models.CharField(max_length=255)),
                ('explication', models.CharField(default='', max_length=1000)),
                ('qcm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MdpEtAuthLv3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('enonce', models.CharField(max_length=255)),
                ('reponse1', models.CharField(max_length=255)),
                ('reponse2', models.CharField(max_length=255)),
                ('reponse3', models.CharField(max_length=255)),
                ('reponce4', models.CharField(max_length=255)),
                ('reponseVrai', models.CharField(max_length=255)),
                ('reponse', models.CharField(max_length=255)),
                ('explication', models.CharField(default='', max_length=1000)),
                ('qcm', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmmea1pourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmmea2pourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmmea3pourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmmeaTpourcentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validemea1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validemea2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validemea3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joueur',
            name='validemeaT',
            field=models.BooleanField(default=False),
        ),
    ]
