# Generated by Django 4.1.7 on 2023-04-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_proteccontrelesmenaceslv2'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='qcmhn1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmhn2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmhn3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmmea1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmmea2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmmea3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmpcm1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmpcm2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='qcmpcm3',
            field=models.FloatField(default=0),
        ),
    ]
